// `.open-next/worker.js` is generated by the Cloudflare build.
// @ts-expect-error The generated module does not exist during editor type resolution.
import openNextWorker from './.open-next/worker.js'

export default {
  async fetch(request, env, context) {
    const url = new URL(request.url)

    if (url.protocol === 'http:') {
      url.protocol = 'https:'

      return new Response(null, {
        headers: {
          'cache-control': 'no-store',
          location: url.toString(),
        },
        status: 308,
      })
    }

    return openNextWorker.fetch(request, env, context)
  },
} satisfies ExportedHandler<CloudflareEnv>
