/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'category-pages': CategoryPage;
    'clef-edit-articles': ClefEditArticle;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'category-pages': CategoryPagesSelect<false> | CategoryPagesSelect<true>;
    'clef-edit-articles': ClefEditArticlesSelect<false> | ClefEditArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'video-section': VideoSection;
    footer: Footer;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'video-section': VideoSectionSelect<false> | VideoSectionSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-pages".
 */
export interface CategoryPage {
  id: number;
  title: string;
  slug: string;
  parentCategory: 'skincare' | 'personal-care' | 'fragrance';
  headerTitle?: string | null;
  headerSubtitle?: string | null;
  headerImage?: (number | null) | Media;
  topMedusaProductHandles?:
    | {
        handle: string;
        id?: string | null;
      }[]
    | null;
  videoTitle?: string | null;
  videoUrl?: string | null;
  videoThumbnail?: (number | null) | Media;
  /**
   * Add, remove, drag to reorder, or disable sections for this category page.
   */
  sections?:
    | {
        section: 'navigation' | 'hero' | 'benefits' | 'products' | 'video' | 'editorial' | 'footer';
        isEnabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clef-edit-articles".
 */
export interface ClefEditArticle {
  id: number;
  title: string;
  slug: string;
  authorName: string;
  authorRole?: string | null;
  authorImage?: (number | null) | Media;
  publishedDate: string;
  categoryLabel: string;
  readTime?: string | null;
  heroImage?: (number | null) | Media;
  description: string;
  questions?:
    | {
        /**
         * Medusa product handle. This makes the recommendation open the live product page.
         */
        productHandle?: string | null;
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  productSuggestions?:
    | {
        name: string;
        price?: string | null;
        description: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  displayOrder: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'category-pages';
        value: number | CategoryPage;
      } | null)
    | ({
        relationTo: 'clef-edit-articles';
        value: number | ClefEditArticle;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-pages_select".
 */
export interface CategoryPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parentCategory?: T;
  headerTitle?: T;
  headerSubtitle?: T;
  headerImage?: T;
  topMedusaProductHandles?:
    | T
    | {
        handle?: T;
        id?: T;
      };
  videoTitle?: T;
  videoUrl?: T;
  videoThumbnail?: T;
  sections?:
    | T
    | {
        section?: T;
        isEnabled?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clef-edit-articles_select".
 */
export interface ClefEditArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  authorName?: T;
  authorRole?: T;
  authorImage?: T;
  publishedDate?: T;
  categoryLabel?: T;
  readTime?: T;
  heroImage?: T;
  description?: T;
  questions?:
    | T
    | {
        productHandle?: T;
        question?: T;
        answer?: T;
        id?: T;
      };
  productSuggestions?:
    | T
    | {
        name?: T;
        price?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  heroButtonLabel?: string | null;
  heroButtonHref?: string | null;
  bestSellerTitle?: string | null;
  /**
   * Paste the Medusa product handle only, for example clef-ocean-elixir-hydrating-cleanser. Do not include /product/ or a leading slash.
   */
  bestSellerMedusaProductHandles?:
    | {
        handle: string;
        id?: string | null;
      }[]
    | null;
  promotionBanners?:
    | {
        title?: string | null;
        subtitle?: string | null;
        /**
         * Add one or more images. Multiple images rotate automatically on the storefront.
         */
        images?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Kept for existing content. It is shown first, followed by any Banner images above.
         */
        image?: (number | null) | Media;
        href?: string | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  newLaunchTitle?: string | null;
  /**
   * Paste Medusa product handles only. Products and prices are always loaded live from Medusa.
   */
  newLaunchMedusaProductHandles?:
    | {
        handle: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Add, remove, drag to reorder, or disable homepage sections. Content for each section is edited in the matching fields on this page.
   */
  sections?:
    | {
        section: 'hero' | 'categories' | 'best-sellers' | 'new-launch' | 'social' | 'testimonials';
        isEnabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Manual homepage video cards only. Add TikTok, Instagram, and Facebook URLs manually; no social media API sync is used.
   */
  homepageVideos?:
    | {
        platform: 'tiktok' | 'instagram' | 'facebook';
        title?: string | null;
        videoUrl?: string | null;
        thumbnail?: (number | null) | Media;
        description?: string | null;
        isActive?: boolean | null;
        displayOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Homepage customer review carousel. Add, edit, reorder, or hide reviews here.
   */
  customerReviews?:
    | {
        name: string;
        role?: string | null;
        review: string;
        avatar?: (number | null) | Media;
        isActive?: boolean | null;
        displayOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manual video entries only. Do not connect this content to official social platform APIs. Frontend rendering should use the first active video per platform.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-section".
 */
export interface VideoSection {
  id: number;
  sectionTitle?: string | null;
  /**
   * Add video URLs manually. Mark one or more active videos per platform and use display order to control which active video appears first.
   */
  videos?:
    | {
        platform: 'tiktok' | 'instagram' | 'facebook';
        title?: string | null;
        videoUrl?: string | null;
        thumbnail?: (number | null) | Media;
        description?: string | null;
        isActive?: boolean | null;
        displayOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  description?: string | null;
  socialLinks?:
    | {
        platform?: ('tiktok' | 'instagram' | 'facebook') | null;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  quickLinks?:
    | {
        label?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroButtonLabel?: T;
  heroButtonHref?: T;
  bestSellerTitle?: T;
  bestSellerMedusaProductHandles?:
    | T
    | {
        handle?: T;
        id?: T;
      };
  promotionBanners?:
    | T
    | {
        title?: T;
        subtitle?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        image?: T;
        href?: T;
        isActive?: T;
        id?: T;
      };
  newLaunchTitle?: T;
  newLaunchMedusaProductHandles?:
    | T
    | {
        handle?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        section?: T;
        isEnabled?: T;
        id?: T;
      };
  homepageVideos?:
    | T
    | {
        platform?: T;
        title?: T;
        videoUrl?: T;
        thumbnail?: T;
        description?: T;
        isActive?: T;
        displayOrder?: T;
        id?: T;
      };
  customerReviews?:
    | T
    | {
        name?: T;
        role?: T;
        review?: T;
        avatar?: T;
        isActive?: T;
        displayOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-section_select".
 */
export interface VideoSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  videos?:
    | T
    | {
        platform?: T;
        title?: T;
        videoUrl?: T;
        thumbnail?: T;
        description?: T;
        isActive?: T;
        displayOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  description?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  quickLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}